spring:
   application:
        name: mailguard

   datasource:
     url: ${db-url}
     username: ${db-uname}
     password: ${db-pass}


   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         format_sql: true
         highlight_sql: true
     show-sql: true

   messages:
     basename: messages


jwt:
  secret: ${jwt-secret}
  expiration: ${jwt-exp} # in milliseconds