spring:
   application:
        name: mailguard

   datasource:
     url: ${db-url}
     username: ${db-uname}
     password: ${db-pass}


   jpa:
     hibernate:
       ddl-auto: update
     properties:
       hibernate:
         format_sql: true
         highlight_sql: true
     show-sql: true

   messages:
     basename: messages


   mail:
     host: ${smtp-host}
     port: ${smtp-port}
     username: ${smtp-uname}
     password: ${smtp-pass}
     properties:
       mail:
         smtp:
           auth: true
           starttls:
             enable: true


jwt:
  secret: ${jwt-secret}
  expiration: ${jwt-exp} # in milliseconds